### ISSUE TITLE
Setup .NET Core T4 templates for Context/Unit of Work data type

### ISSUE THREAD

**Issue by rossleem** [laredoza/.NetScaffolder#49]

**Comment by laredoza** [comment]
This will be useful for the core migration:

https://blog.devart.com/migrating-entity-framework-6-projects-to-entity-framework-core-1-entity-framework-7.html

**Comment by laredoza** [comment]
Implement both SqlServer and MySql. Oracle will only be available 3rd quater of this year in Beta
