### ISSUE TITLE
Setup .NET Core T4 templates for Entity data type

### ISSUE THREAD

**Issue by rossleem** [laredoza/.NetScaffolder#51]

**Comment by rossleem** [comment]
Adding as a placeholder, but probably not required

**Comment by rossleem** [comment]
Added as a placeholder, but may not be required

**Comment by laredoza** [comment]
Hi @rossleem , fixed the relationship generation but I've had to included the DotNetScaffolder.Mapping.ApplicationServices.dll in the Package Folder. Not sure if it should be copied on builds?

**Comment by laredoza** [comment]
Closing as this isn't required any more
